x-backend-environment: &backend-environment
  - HELM_API_KEY=${HELM_API_KEY}
  - OPENAI_API_KEY=${OPENAI_API_KEY}
  - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
  - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
  - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
  - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
  - GOOGLE_API_KEY=${GOOGLE_API_KEY}
  - TOGETHER_API_KEY=${TOGETHER_API_KEY}
  - BOUNTYBENCH_DISABLE_KALI_DOCKER=${BOUNTYBENCH_DISABLE_KALI_DOCKER:-1}

services:
  nginx:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      container_name: nginx-proxy
      ports:
        - "3000:80"  # Host port 3000 to Container port 80
      depends_on:
        - frontend
        - backend
      networks:
        - app-network

  backend:
    image: bountybench-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-service
    privileged: true
    volumes:
      - dind-data:/var/lib/docker
      - ./logs:/app/logs
      - ./full_logs:/app/full_logs
      - ./prompts/teacher_agent_system_prompt.txt:/app/prompts/teacher_agent_system_prompt.txt:ro
      - ./prompts/system_prompts:/app/prompts/system_prompts:ro
      # Please uncomment the following lines if you need to mount SSH keys for the backend service
      # - ${HOME}/.ssh/id_rsa_backend-service:/root/.ssh/id_rsa:ro
      # - ${HOME}/.ssh/id_rsa_backend-service.pub:/root/.ssh/id_rsa.pub:ro
    networks:
      - app-network
    environment: *backend-environment

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend-service
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_USE_NGINX_PROXY=true # The REACT_APP_ prefix exposes the variable to the frontend JS code
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dind-data:
    name: dind-data
